repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        require_serial: true

      - id: prospector
        name: prospector
        entry: uv run prospector
        language: system
        types: [python]
        require_serial: true

      - id: mypy
        name: mypy
        entry: uv run mypy --config-file mypy.ini .
        language: system
        pass_filenames: false
        require_serial: true

      - id: pytest
        name: pytest
        entry: uv run pytest --override-ini=addopts=
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
