[mypy]
python_version = 3.14
ignore_missing_imports = True
warn_return_any = True
warn_unused_configs = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
strict_equality = True
exclude = ^(venv/|\.venv/)

[mypy-framework.*]
implicit_reexport = True

[mypy-venv.*]
ignore_errors = True

[mypy-.venv.*]
ignore_errors = True
